---
settings:
  name: NetApp Ransomware Resilience
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentación NetApp Ransomware Resilience
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades en resiliencia frente al ransomware
      url: "/whats-new.html"
    - title: Limitaciones conocidas
      url: "/rp-reference-limitations.html"
  - title: Empezar
    entries:
    - title: Aprenda sobre la resiliencia frente al ransomware
      url: "/concept-ransomware-resilience.html"
    - title: Prerrequisitos
      url: "/rp-start-prerequisites.html"
    - title: Inicio rápido
      url: "/rp-start-quick-start.html"
    - title: Configurar la resiliencia frente al ransomware
      url: "/rp-start-setup.html"
    - title: Acceda a la resiliencia frente al ransomware
      url: "/rp-start-login.html"
    - title: Configurar licencias
      url: "/rp-start-licenses.html"
    - title: Descubra las cargas de trabajo
      url: "/rp-start-discover.html"
    - title: Simular un ataque de ransomware con un simulacro de preparación
      url: "/rp-start-simulate.html"
    - title: Configurar copias de seguridad, detección de amenazas y simulaciones
        de ataques en Configuración
      url: "/rp-use-settings.html"
    - title: Configurar la detección de actividad sospechosa de usuarios
      url: "/suspicious-user-activity.html"
  - title: Utilice la resiliencia frente al ransomware
    entries:
    - title: Descripción general del uso de la resiliencia frente al ransomware
      url: "/rp-use-overview.html"
    - title: Visualizar el estado de la carga de trabajo mediante el Panel de control
      url: "/rp-use-dashboard.html"
    - title: Proteger las cargas de trabajo
      entries:
      - title: Proteja las cargas de trabajo con estrategias de protección contra
          ransomware
        url: "/rp-use-protect.html"
      - title: Escanear en busca de datos de identificación personal
        url: "/rp-use-protect-classify.html"
    - title: Responder a una alerta detectada
      url: "/rp-use-alert.html"
    - title: Recuperarse de un ataque de ransomware
      url: "/rp-use-recover.html"
    - title: Descargar informes
      url: "/rp-use-reports.html"
  - section: support
  - title: Preguntas frecuentes
    url: "/rp-start-faq.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
