---
settings:
  name: NetApp Ransomware Resilience
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    release_notes_repo: console-relnotes
  rss_page: whats-new.html
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentación NetApp Ransomware Resilience
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades en resiliencia frente al ransomware
      url: "/whats-new.html"
    - title: Limitaciones conocidas
      url: "/rp-reference-limitations.html"
  - title: Empezar
    entries:
    - title: Aprenda sobre la resiliencia frente al ransomware
      url: "/concept-ransomware-resilience.html"
    - title: Prerrequisitos
      url: "/rp-start-prerequisites.html"
    - title: Inicio rápido
      url: "/rp-start-quick-start.html"
    - title: Configurar la resiliencia frente al ransomware
      url: "/rp-start-setup.html"
    - title: Configurar licencias
      url: "/rp-start-licenses.html"
    - title: Descubra las cargas de trabajo
      url: "/rp-start-discover.html"
  - title: Utilice la resiliencia frente al ransomware
    entries:
    - title: Acceda a la resiliencia frente al ransomware
      url: "/rp-start-login.html"
    - title: Ver la salud de la carga de trabajo
      url: "/rp-use-dashboard.html"
    - title: Protégete y detecta
      entries:
      - title: Revisa la protección
        url: "/task-review-protection.html"
      - title: Configurar destinos de respaldo
        url: "/task-backup-destination.html"
      - title: Proteger las cargas de trabajo
        url: "/rp-use-protect.html"
      - title: Configura la detección de la actividad de los usuarios
        entries:
        - title: Conoce la detección de la actividad de los usuarios
          url: "/concept-user-behavior.html"
        - title: Requisitos para la detección de la actividad de usuario
          url: "/reference-user-activity-requirements.html"
        - title: Configura agentes y colectores
          url: "/suspicious-user-activity.html"
      - title: Gestiona grupos de protección
        url: "/task-protection-group.html"
      - title: Escanear en busca de datos de identificación personal
        url: "/task-classify.html"
    - title: Responder y recuperarse
      entries:
      - title: Responder a una alerta detectada
        url: "/rp-use-alert.html"
      - title: Recuperarse de un ataque de ransomware
        url: "/rp-use-recover.html"
    - title: Realiza un simulacro de preparación
      url: "/rp-start-simulate.html"
    - title: Configura SIEM
      url: "/task-siem.html"
    - title: Descargar informes
      url: "/rp-use-reports.html"
  - section: support
  - title: Preguntas frecuentes
    url: "/rp-start-faq.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
