---
sidebar: sidebar 
permalink: rp-reference-limitations.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto. 
---
= Limitaciones conocidas en NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o que no interoperan correctamente con él. Revise estas limitaciones cuidadosamente.



[[readiness-drill-reset-option-issue]]
== Problema con la opción de reinicio del simulacro de preparación

Si selecciona un volumen ONTAP 9.11.1 para el simulacro de preparación para ataques de ransomware, Ransomware Resilience envía una alerta.  Si recupera los datos utilizando la opción "clonar a volumen" y reinicia el taladro, la operación de reinicio falla.



[[amazon-fsx-for-netapp-ontap-limitations]]
== Limitaciones de Amazon FSx for NetApp ONTAP

Las siguientes limitaciones se aplican a Amazon FSx para ONTAP:

* Las políticas de backup no son compatibles con Amazon FSx for ONTAP. En este entorno, debes realizar las operaciones de backup usando las copias de seguridad de Amazon FSx. Puedes restaurar estas cargas de trabajo usando Ransomware Resilience.
* Las operaciones de restauración se realizan únicamente desde instantáneas.




[[azure-netapp-files-limitations]]
== Limitaciones de Azure NetApp Files

Las siguientes limitaciones aplican a Azure NetApp Files:

* Las estrategias de protección contra ransomware con políticas de backup no son compatibles con Azure NetApp Files. En su lugar, puedes usar el backup de Azure NetApp Files.
* Las estrategias de protección contra ransomware con replicación no son compatibles para Azure NetApp Files.
* Azure NetApp Files no es compatible con FPolicy ni con la detección del comportamiento del usuario. Azure NetApp Files tampoco es compatible con la entropía forense.
* Al seleccionar una estrategia de protección, asegúrate de que su planificación de instantáneas sea compatible con Azure NetApp Files. La planificación de instantáneas más frecuente disponible en Azure NetApp Files es horaria.
* Se recomienda no utilizar link:reference-soar.html["Playbooks SOAR"] con Azure NetApp Files debido a que las API de Azure NetApp Files bloquean las acciones automatizadas.
* Algunos datos de eventos no se incluyen en link:task-siem.html["Informes SIEM"] para configuraciones de Azure NetApp Files.




[[google-cloud-netapp-volumes-limitations]]
== Limitaciones de Google Cloud NetApp Volumes

Las siguientes limitaciones se aplican a Google Cloud NetApp Volumes:

* Actualmente, solo puedes aplicar estrategias de protección basadas en cifrado y FPolicy a las cargas de trabajo de Google Cloud NetApp Volumes. No puedes aplicar estrategias de protección del comportamiento del usuario.
* Actualmente, las estrategias de protección con replicación no son compatibles con Google Cloud NetApp Volumes.




[[san-storage-limitations]]
== Limitaciones del almacenamiento SAN

Las siguientes limitaciones se aplican a las cargas de trabajo de SAN (almacenamiento en bloques):

* Cuando Ransomware Resilience genera alertas para cargas de trabajo SAN, dichas alertas se basan únicamente en una entropía elevada.
* Las cargas de trabajo SAN solo se pueden restaurar usando un link:task-custom-restore.html["restauración personalizada"]. La restauración limpia no está disponible actualmente para las cargas de trabajo SAN.




[[multi-admin-verification]]
== Verificación multiadministrador

La verificación de múltiples administradores no es compatible con Ransomware Resilience ni con la NetApp Console. Si has configurado link:https://docs.netapp.com/us-en/ontap/multi-admin-verify/["Verificación multi-admin en ONTAP"^], no podrás habilitar la protección, realizar un simulacro de preparación ni llevar a cabo ninguna operación de restauración. Debes desactivar la verificación de múltiples administradores antes de intentar cualquiera de estas operaciones.
