---
sidebar: sidebar 
permalink: rp-reference-limitations.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto. 
---
= Limitaciones conocidas de NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o que no interoperan correctamente con él. Revise estas limitaciones cuidadosamente.



== Problema con la opción de reinicio del ejercicio de preparación

Si selecciona un volumen ONTAP 9.11.1 para el simulacro de preparación para ataques de ransomware, Ransomware Resilience envía una alerta.  Si recupera los datos utilizando la opción "clonar a volumen" y reinicia el taladro, la operación de reinicio falla.



== Limitaciones de Amazon FSx for NetApp ONTAP

El sistema Amazon FSx for NetApp ONTAP es compatible con Ransomware Resilience. Las siguientes limitaciones se aplican a Amazon FSx para ONTAP:

* Las políticas de backup no son compatibles con Amazon FSx for ONTAP. En este entorno, deberías realizar las operaciones de backup usando Amazon FSx for backups. Puedes restaurar estas cargas de trabajo usando Ransomware Resilience.
* Las operaciones de restauración se realizan únicamente desde instantáneas.




== Limitaciones de Azure NetApp Files

Azure NetApp Files es compatible con Ransomware Resilience. Las siguientes limitaciones aplican a Azure NetApp Files:

* Las estrategias de protección contra ransomware con políticas de backup no son compatibles con Azure NetApp Files. En su lugar, puedes usar el backup de Azure NetApp Files.
* Las estrategias de protección contra ransomware con replicación no son compatibles para Azure NetApp Files.
* Al seleccionar una estrategia de protección, asegúrate de que su planificación de instantáneas sea compatible con Azure NetApp Files. La planificación de instantáneas más frecuente disponible en Azure NetApp Files es horaria.

