---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: Encuentre una respuesta a una pregunta frecuente sobre NetApp Ransomware Resilience. 
---
= Preguntas frecuentes sobre la NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Estas preguntas frecuentes pueden ser útiles si simplemente busca una respuesta rápida a una pregunta sobre NetApp Ransomware Resilience.



== Despliegue

.¿Necesita una licencia para usar Ransomware Resilience?
Puede utilizar los siguientes tipos de licencia:

* Regístrese para una prueba gratuita de 30 días.
* Compre una suscripción de pago por uso (PAYGO) a NetApp Intelligent Services y Ransomware Resilience con Amazon Web Services (AWS) Marketplace, Google Cloud Marketplace y Microsoft Azure Marketplace.
* Traiga su propia licencia (BYOL), que es un archivo de licencia de NetApp (NLF) que obtiene de su representante de ventas de NetApp . Puedes usar el número de serie de la licencia para activar BYOL en la sección Licenses and subscriptions de la consola.


.¿Cómo se habilita la resiliencia ante el ransomware?
Puede acceder a Ransomware Resilience desde la NetApp Console. Asegúrate de haber link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["roles de acceso"] y link:rp-start-prerequisites.html["prerrequisitos"]. Si ha configurado correctamente un agente de consola, podrá entonces link:rp-start-discover.html["descubrir cargas de trabajo"].

Para obtener más información, consultelink:rp-start-login.html["Acceda a la resiliencia frente al ransomware"] ylink:rp-start-quick-start.html["Guía de inicio rápido sobre resiliencia ante el ransomware"] .

.¿Está disponible la resiliencia ante el ransomware en modos estándar, restringido y privado?
Actualmente, la función de Resiliencia ante Ransomware solo está disponible en modo estándar.

Para obtener una explicación sobre estos modos en todos los servicios de datos de NetApp , consulte https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modos de implementación de la NetApp Console"^] .

.¿Cómo funciona la facturación de Ransomware Resilience?
Puedes probar Ransomware Resilience con una prueba gratuita de 30 días. NetApp no ​​le cobra por utilizar la versión de prueba de Ransomware Resilience.

Si tiene Backup and Recovery y Ransomware Resilience, cualquier dato común protegido por ambos productos se factura únicamente por Ransomware Resilience.

Cuando una carga de trabajo se clasifica como protegida, cuenta contra la capacidad adquirida o la suscripción PAYGO. Ransomware Resilience clasifica una carga de trabajo como protegida cuando se habilita una política de detección con al menos una política de instantáneas o de backup. Las cargas de trabajo descubiertas con una política de detección pero _sin_ políticas de backup o instantáneas se clasifican como en riesgo. Las cargas de trabajo en riesgo no cuentan contra la capacidad adquirida.

Las cargas de trabajo protegidas cuentan contra la capacidad adquirida o la suscripción después de que termine el periodo de prueba gratuito. Ransomware Resilience se cobra por GB para los datos asociados con las cargas de trabajo protegidas (según lo reporta ONTAP) antes de las eficiencias.



== Acceso

.¿Cuál es la URL de Resiliencia contra el Ransomware?
En un navegador, ingrese https://console.netapp.com/["https://console.netapp.com/ransomware-resilience"^] para acceder a la consola.

.¿Cómo se gestionan los permisos de acceso?
https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la consola para todos los servicios"^]. La resiliencia ante el ransomware también tiene link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-ransomware-roles.html["roles de acceso dedicados"^].

.¿Qué resolución de dispositivo es la mejor?
La resolución de dispositivo recomendada para Ransomware Resilience es 1920x1080 o superior.

.¿Qué navegador debo usar?
Puedes acceder a la NetApp Console con cualquier navegador web moderno.



== Interoperabilidad

.¿Ransomware Resilience conoce las configuraciones de protección en ONTAP?
Sí, Ransomware Resilience descubre programaciones de instantáneas configuradas en ONTAP.

.¿Cómo interactúa Ransomware Resilience con NetApp Backup and Recovery?
Ransomware Resilience trabaja con Backup and Recovery para descubrir y establecer políticas de instantáneas y copias de seguridad para cargas de trabajo de archivos compartidos. Ransomware Resilience también trabaja con Backup and Recovery para realizar la recuperación coherente de archivos y cargas de trabajo.

Para licencias y facturación, Ransomware Resilience puede integrarse con Backup and Recovery incluso si no tiene una licencia separada para Backup and Recovery. Si tiene Backup and Recovery y Ransomware Resilience, cualquier dato común protegido por ambos productos se factura únicamente por Ransomware Resilience.



== Cargas de trabajo

.¿Qué se entiende por carga de trabajo en el contexto de la resiliencia ante el ransomware?
Una carga de trabajo es una aplicación, una máquina virtual o un recurso compartido de archivos. Una carga de trabajo incluye todos los volúmenes que utiliza una única instancia de aplicación.

Por ejemplo, considere una base de datos Oracle implementada en ora3.host.com con `vol1` que contienen datos y `vol2` Contiene registros. Los dos volúmenes constituyen la carga de trabajo para esa instancia de Oracle Database.

.¿Cómo prioriza Ransomware Resilience los datos de la carga de trabajo?
La prioridad de la carga de trabajo (crítica, estándar, importante) está determinada por las frecuencias de instantáneas ya aplicadas a cada volumen asociado con la carga de trabajo y las copias de seguridad programadas.

link:rp-use-protect.html["Obtenga información sobre la prioridad o importancia de la carga de trabajo"] .

.¿Qué cargas de trabajo admite Ransomware Resilience?
Ransomware Resilience puede identificar las siguientes cargas de trabajo: Oracle, recursos compartidos de archivos, almacenamiento en bloque, máquinas virtuales y almacenes de datos de máquinas virtuales.

.¿Cómo se asocian los datos a una carga de trabajo?
Ransomware Resilience descubre los volúmenes y las extensiones de archivo y los asocia con la carga de trabajo apropiada.

.¿Qué es una carga de trabajo protegida?
En Ransomware Resilience, una carga de trabajo muestra el estado *protegida* cuando tiene habilitada una política de _detección_ primaria, lo que significa link:concept-ransomware-resilience.html["Protección autónoma contra el ransomware (ARP)"] está habilitado en todos los volúmenes relacionados con la carga de trabajo.

.¿Qué es una carga de trabajo "en riesgo"?
Si una carga de trabajo no tiene habilitada una política de detección primaria, se la etiqueta como "en riesgo" incluso si tiene habilitada una política de copia de seguridad y de instantáneas. Para protegerte del ransomware, debes habilitar una link:rp-use-protect.html#add-a-ransomware-protection-strategy["política de detección"].

.He añadido un nuevo volumen, pero aún no aparece. ¿Qué tengo que hacer?
Si ha añadido un nuevo volumen a su entorno, vuelva a iniciar la detección de la carga de trabajo. Una vez descubierto el volumen, link:rp-use-protect.html#add-a-ransomware-protection-strategy["Aplicar políticas de protección para proteger el nuevo volumen"].



== Políticas de protección

.¿Las políticas de resiliencia ante el ransomware coexisten con otros tipos de políticas de carga de trabajo?
En este momento, Backup and Recovery (Cloud Backup) admite una política de backup por volumen. Si configura la protección de copias de seguridad con Copia de seguridad y recuperación, comparte las políticas de copia de seguridad con Resiliencia contra ransomware.

Las copias instantáneas no están limitadas y se pueden agregar por separado desde cada servicio.

.¿Qué políticas son necesarias en una estrategia de protección contra el ransomware?
A link:rp-use-protect.html#add-a-ransomware-protection-strategy["estrategia de protección contra el ransomware"] Requisitos:

* una política de detección de ransomware, y
* una política de instantáneas


No se requiere una política de respaldo en la estrategia de resiliencia frente al ransomware.

.¿Ransomware Resilience conoce las configuraciones de protección en ONTAP?
Sí, Ransomware Resilience descubre las programaciones de instantáneas establecidas en ONTAP. También descubre si ARP y FPolicy están activados en todos los volúmenes de una carga de trabajo descubierta. La información que ves en el panel de Ransomware Resilience se agrega a partir de otras soluciones y productos de NetApp.

.¿Ransomware Resilience reconoce las políticas que ya se han creado en NetApp Backup and Recovery?
Sí, si tienes cargas de trabajo gestionadas en Backup and Recovery, las políticas gestionadas por esos productos se incorporan a Ransomware Resilience.

.¿Puedes modificar las políticas transferidas de NetApp Backup and Recovery?
No, no puedes modificar las políticas gestionadas por Backup and Recovery desde Ransomware Resilience. Tú gestionas cualquier cambio en esas políticas en Backup and Recovery.

.Si existen políticas de ONTAP (como ARP, FPolicy y snapshots), ¿se modifican en Ransomware Resilience?
No. Ransomware Resilience no modifica ninguna política de detección existente (configuración ARP, FPolicy) de ONTAP.

.¿Qué pasa si añades nuevas políticas en Backup and Recovery después de registrarte en Ransomware Resilience?
Ransomware Resilience reconoce las políticas de nueva creación y los cambios de política en Backup and Recovery.

.¿Se pueden cambiar las políticas desde ONTAP?
Sí, puede cambiar las políticas de ONTAP en Ransomware Resilience.  También puede crear nuevas políticas en Ransomware Resilience y aplicarlas a las cargas de trabajo.  Esta acción reemplaza las políticas ONTAP existentes con las políticas creadas en Ransomware Resilience.

.¿Se pueden deshabilitar las políticas en ONTAP?
Puede deshabilitar ARP en las políticas de detección utilizando la interfaz de usuario, las API o la CLI del administrador del sistema en ONTAP.

Puede deshabilitar FPolicy y las políticas de respaldo aplicando una política diferente que no las incluya.
