---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: Para utilizar Ransomware Resilience, realice unos pocos pasos para configurarlo. 
---
= Configurar NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Configura NetApp Ransomware Resilience preparando un destino de copia de seguridad, revisando los requisitos previos y configurando la NetApp Console y el agente de Console.



[[prepare-the-backup-destination]]
== Preparar el destino de la copia de seguridad

Prepare uno de los siguientes destinos de respaldo:

* StorageGRID en NetApp
* Servicios web de Amazon
* Plataforma de Google Cloud
* Microsoft Azure


Después de configurar las opciones en el propio destino de backup, luego lo vas a configurar como destino de backup en Ransomware Resilience. Para detalles sobre cómo configurar el destino de backup en Ransomware Resilience, consulta link:task-backup-destination.html["Configurar destinos de respaldo"].



[[prepare-storagegrid-to-become-a-backup-destination]]
=== Prepare StorageGRID para que se convierta en un destino de respaldo

Si desea utilizar StorageGRID como destino de su copia de seguridad, consulte https://docs.netapp.com/us-en/storagegrid-117/index.html["Documentación de StorageGRID"^] para obtener detalles sobre StorageGRID.



[[prepare-aws-to-become-a-backup-destination]]
=== Prepare AWS para convertirse en un destino de respaldo

* Configurar una cuenta en AWS.
* Configurar https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Permisos de AWS"^] en AWS.


Para obtener detalles sobre cómo administrar su almacenamiento de AWS en la consola, consulte https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["Administra tus buckets de Amazon S3"^] .



[[prepare-azure-to-become-a-backup-destination]]
=== Prepare Azure para convertirse en un destino de respaldo

* Configurar una cuenta en Azure.
* Configurar https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Permisos de Azure"^] en Azure.


Para obtener detalles sobre cómo administrar su almacenamiento de Azure en la consola, consulte https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["Administrar sus cuentas de almacenamiento de Azure"^] .



[[set-up-the-netapp-console]]
== Configurar la NetApp Console

El siguiente paso es configurar la NetApp Console y NetApp Ransomware Resilience.

Revisar https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Requisitos de consola para el modo estándar"^] .



[[create-a-console-agent]]
=== Crear un agente de consola

Ponte en contacto con tu representante comercial de NetApp para probar o utilizar este servicio. Luego, el agente de Console incluye las funciones necesarias para Ransomware Resilience.

Para crear un agente de Console para Ransomware Resilience, ponte en contacto con el administrador de tu organización de Console que tenga permiso para crear agentes de Console y consulta https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Cómo crear un agente de consola"^].


NOTE: Si tienes varios agentes de la Console, Ransomware Resilience analiza los datos de todos los agentes de la Console, no solo del que se muestra actualmente en la Console. El servicio analiza los datos de todos los proyectos y agentes de la Console asociados con la organización.
