---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: bluexp ransomware protection, ransomware protection prerequisites, resilience 
summary: Comience a utilizar NetApp Ransomware Resilience verificando la compatibilidad con su entorno, acceso a la red, inicio de sesión y navegador web. 
---
= Requisitos previos de NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Para garantizar el éxito de la implantación de NetApp Ransomware Resilience, verifica que tu entorno operativo, el acceso a la red y el navegador web estén listos.

Revisa y asegúrate de cumplir con los siguientes requisitos.



== Sistemas compatibles

Asegúrese de estar utilizando un sistema compatible:

|===
| Ambiente | Protocolo | Versiones compatibles 


| Amazon FSx for NetApp ONTAP | CIFS, NFS y SAN | N/A 


| Azure NetApp Files | CIFS y NFS | N/A 


.2+| Cloud Volumes ONTAP para AWS | CIFS y NFS | 9.11.1 y posteriores 


| SAN (iSCSI y NVMe) | 9.17.1 y posteriores 


.2+| Cloud Volumes ONTAP para Google Cloud Platform | CIFS y NFS | 9.11.1 y posteriores 


| SAN (iSCSI y NVMe) | 9.17.1 y posteriores 


.2+| Cloud Volumes ONTAP para Microsoft Azure | CIFS y NFS | 9.12.1 y posteriores 


| SAN (iSCSI y NVMe) | 9.17.1 y posteriores 


.2+| ONTAP (en las instalaciones) | CIFS y NFS | 9.11.1 y posteriores 


| SAN (iSCSI y NVMe) | 9.17.1 y posteriores 


| Google Cloud NetApp Volumes | CIFS, NFS, SAN (iSCSI y NVMe) | N/A 
|===

NOTE: La detección de actividad del usuario no es compatible con Azure NetApp Files o Google Cloud NetApp Volumes. Para obtener más información sobre la compatibilidad con la detección de actividad del usuario, consulta link:reference-user-activity-requirements.html["Requisitos para la detección de la actividad de usuario"].



== Requisitos de la NetApp Console

La configuración de su NetApp Console requiere:

* Una cuenta de usuario de la NetApp Console con privilegios de administrador de la organización para descubrir recursos.
* Una organización y sistema de consola con al menos un agente de consola activo conectado a unalink:concept-ransomware-resilience.html#supported-backup-targets-systems-and-workload-data-sources["sistema compatible"] .
+
** Si tus clústeres ONTAP locales o sistemas Cloud Volumes ONTAP no están configurados en la NetApp Console, consulta link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Aprenda a configurar un agente de consola"^] y link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisitos estándar de la consola"^].
+

NOTE: Si tienes varios agentes de Console en una única organización de Console, Ransomware Resilience analizará los recursos de ONTAP en todos los agentes de Console además del que esté seleccionado actualmente en la interfaz de usuario de Console.



* El agente de consola debe tener la `cloudmanager-ransomware-protection` contenedor en estado activo.
* Hay un límite de 3,000 cargas de trabajo por agente de Console.
* Para clústeres ONTAP o Cloud Volumes ONTAP, Ransomware Resilience requiere ONTAP versión 9.11.1 o superior.
+

NOTE: Para utilizar la resiliencia contra el ransomware en cargas de trabajo SAN, debe estar ejecutando ONTAP 9.17.1 o posterior.





== Requisitos de ONTAP

* Debe estar ejecutando ONTAP 9.11.1 o posterior con una licencia ONTAP One habilitada en la instancia ONTAP local.  Para obtener más información sobre la compatibilidad con ONTAP , consultelink:https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Descripción general de la protección autónoma contra ransomware"^] .
* Para aplicar configuraciones de protección (como habilitar la protección autónoma contra ransomware), Ransomware Resilience necesita permisos de administrador en el clúster ONTAP . El clúster ONTAP debería haberse incorporado utilizando únicamente las credenciales de usuario administrador del clúster ONTAP .



NOTE: Si has conectado un clúster ONTAP a la consola con credenciales que no son de administrador, debes <<Actualizar los permisos de usuarios no administradores en un sistema ONTAP>>.



== Copias de seguridad de datos

* Una cuenta en NetApp StorageGRID, AWS S3, Azure Blob o Google Cloud Platform para destinos de copia de seguridad con los permisos de acceso adecuados configurados.
+
Consulte la https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Lista de permisos de AWS, Azure o S3"^] Para más detalles.




NOTE: Puedes link:task-backup-destination.html["configurar un destino de backup en Ransomware Resilience"]. Si tus cargas de trabajo están protegidas por NetApp Backup and Recovery, Ransomware Resilience reconoce automáticamente los detalles de protección, incluidas las instantáneas y los destinos de backup. Backup and Recovery _no_ es necesario para usar Ransomware Resilience.



== Requisitos para la detección del comportamiento de los usuarios

Para que Ransomware Resilience proporcione alertas sobre el comportamiento del usuario, debes configurar un agente de actividad del usuario. Para instalar un agente de actividad del usuario, asegúrate de que tu sistema cumple link:reference-user-activity-requirements.html["los requisitos"].



== Requisitos previos para la restauración limpia

Ransomware Resilience proporciona restauraciones limpias, que ofrecen un proceso de recuperación guiado que descubre las vías de recuperación óptimas. Para utilizar la restauración limpia, link:task-clean-restore.html["asegúrate de cumplir los requisitos previos"].



== Actualizar los permisos de usuarios no administradores en un sistema ONTAP

Si necesitas actualizar los permisos de usuarios no administradores para un sistema en particular, usa este procedimiento:

. Inicia sesión en la consola. En el panel de control, identifica el sistema que necesita que se actualicen sus permisos de usuario de ONTAP.
. Selecciona el sistema para ver sus detalles.
. Seleccione *Ver información adicional* para mostrar el nombre de usuario.
. Inicie sesión en la CLI del clúster ONTAP como usuario administrador.
. Muestra los roles existentes para ese usuario:
+
[listing]
----
security login show -user-or-group-name <username>
----
. Cambiar el rol del usuario. Ingresar:
+
[listing]
----
security login modify -user-or-group-name <name> -application console|http|ontapi|ssh -authentication-method password -role admin
----
. Vuelva a la NetApp Console para usar la función de resiliencia ante ransomware.

