= Evaluación de riesgos de seguridad de Digital Advisor
:allow-uri-read: 




[[security-risk-assessment-from-digital-advisor]]
=== Evaluación de riesgos de seguridad de Digital Advisor

La protección contra ransomware de BlueXP ahora recopila información sobre riesgos de seguridad altos y críticos del clúster de NetApp Digital Advisor. Si se detecta un riesgo, la protección contra ransomware de BlueXP muestra esta recomendación en el panel *Acciones recomendadas* del panel de control: "Soluciona una vulnerabilidad de seguridad conocida en el clúster <name>." Desde la recomendación del panel de control, selecciona *Revisar y solucionar* para revisar Digital Advisor y el artículo relacionado de Common Vulnerability & Exposure (CVE). Si hay varios riesgos de seguridad, revisa los detalles en Digital Advisor.

Referirse a https://docs.netapp.com/us-en/active-iq/index.html["Documentación de Digital Advisor"^] .



[[back-up-to-google-cloud-platform]]
=== Realizar copias de seguridad en Google Cloud Platform

Con esta versión, puedes establecer un destino de respaldo en un depósito de Google Cloud Platform.  Anteriormente, solo podía agregar destinos de respaldo a NetApp StorageGRID, Amazon Web Services y Microsoft Azure.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-backup-destination.html["Obtenga más información sobre cómo configurar los ajustes de BlueXP ransomware protection"].



[[support-for-google-cloud-platform]]
=== Compatibilidad con Google Cloud Platform

El servicio ahora es compatible con Cloud Volumes ONTAP para Google Cloud Platform para la protección del almacenamiento.  Anteriormente, el servicio solo admitía Cloud Volumes ONTAP para Amazon Web Services y Microsoft Azure junto con NAS local.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Obtenga información sobre la BlueXP ransomware protection y las fuentes de datos compatibles, los destinos de copia de seguridad y los entornos de trabajo."] .



[[role-based-access-control]]
=== Control de acceso basado en roles

Ahora puede limitar el acceso a actividades específicas con el control de acceso basado en roles (RBAC).  La BlueXP ransomware protection utiliza dos roles de BlueXP: administrador de cuenta de BlueXP y administrador sin cuenta (visor).

Para obtener detalles sobre las acciones que puede realizar cada rol, consulte https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["Privilegios de control de acceso basados en roles"] .
