= Mayor flexibilidad para las estrategias de protección
:allow-uri-read: 




[[enhanced-flexibility-for-protection-strategies]]
=== Mayor flexibilidad para las estrategias de protección

Ransomware Resilience ofrece ahora más flexibilidad a la hora de elegir estrategias de detección de ransomware. Anteriormente, todas las estrategias de protección contra ransomware tenían que incluir la detección de cifrado. Ahora, puedes activar una estrategia de protección contra ransomware solo con la detección del comportamiento del usuario.

Las estrategias de protección pueden incluir tanto la detección de cifrado _como_ la detección de comportamientos sospechosos de los usuarios. El bloqueo de extensiones de archivo también puede añadirse a cualquier estrategia de protección.

Si desactivas parte de la estrategia de protección para una política existente, cualquier alerta existente creada bajo la iteración anterior de la política solo puede marcarse como "Resuelta" y no como "Descartada". Por ejemplo, si tenías una estrategia de protección que incluía detección de cifrado y comportamiento sospechoso del usuario pero desactivas la detección de cifrado, solo puedes resolver una alerta de cifrado existente para esa carga de trabajo.

Para obtener más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["Proteja las cargas de trabajo con las estrategias de protección NetApp Ransomware Resilience"^].



[[soar-playbook-enhancements]]
=== Mejoras en el playbook SOAR

Los manuales SOAR de resiliencia al ransomware ahora proporcionan pasos de corrección después de que hayas bloqueado a un usuario o puesto un volumen fuera de línea. Ahora puedes volver a poner un volumen en línea y desbloquear a un usuario si la acción no se consideró una amenaza de ransomware.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Integra un playbook SOAR"^].
