= Excluir usuarios de forma masiva de las alertas de comportamiento del usuario
:allow-uri-read: 




[[bulk-exclude-users-from-user-behavior-alerts]]
=== Excluir usuarios de forma masiva de las alertas de comportamiento del usuario

Ransomware Resilience ahora admite la carga de una lista JSON de usuarios para excluir de las alertas de comportamiento del usuario, además de las opciones existentes basadas en la interfaz de usuario y en CSV.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html#exclude-users-from-alerts["Excluir usuarios de alertas"^].



[[user-behavior-detection-enhancements]]
=== Mejoras en la detección del comportamiento de los usuarios

Ransomware Resilience ha mejorado la información sobre el comportamiento de los usuarios al añadir alertas por correo electrónico e incluir eventos de comportamiento de usuario en los datos de eventos SIEM compatibles (AWS Security Hub, Microsoft Sentinel y Splunk Cloud). Estas mejoras ofrecen información más precisa sobre tu supervisión de seguridad y cumplimiento.

Para más información, consulta link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html["Conecta NetApp Ransomware Resilience a un SIEM"^].
